### ISSUE TITLE
Major Features TODO

### ISSUE THREAD

**Issue by FBartos** [jasp-stats/jaspMetaAnalysis#265]
- [ ] failsafe N (https://github.com/jasp-stats/jasp-issues/issues/141)
- [ ] trim & fill
- [ ] vcalc / rcalc integration into multilevel/multivariate meta-analysis
- [ ] frequentist binomial meta-analysis
- [ ] selection models based on metafor
- [ ] Bayesian model-averaged meta-regression 
- [ ] Bayesian multilevel/multivariate models
- [ ] psychometric meta-analysis (https://github.com/jasp-stats/jasp-issues/issues/115)
- [ ] network meta-analysis (https://github.com/jasp-stats/jasp-issues/issues/1646)
- [ ] meta-analytic sem (https://github.com/jasp-stats/jasp-issues/issues/2103)
- [ ] multiple imputation
- [ ] analysis stratification (https://github.com/jasp-stats/INTERNAL-jasp/issues/1147, https://github.com/jasp-stats/jasp-issues/issues/1010)
- [ ] effect size transformations
- [ ] risk of bias visualization
- [ ] z-curve (https://github.com/jasp-stats/jasp-issues/issues/1634)

**Comment by tomtomme** [comment]
@FBartos 
Me and my colleagues are currently in a review process for a Meta-Analysis and of course we used JASP for this. Now the editor is asking for R Syntax and I just now realized that Meta-Analysis is one of the modules not yet offering it. Is there work in progress somewhere or a plan / time horizont on implementing this?

**Comment by FBartos** [comment]
> @FBartos 
> Me and my colleagues are currently in a review process for a Meta-Analysis and of course we used JASP for this. Now the editor is asking for R Syntax and I just now realized that Meta-Analysis is one of the modules not yet offering it. Is there work in progress somewhere or a plan / time horizont on implementing this?

Could you please ask @boutinb  for this? He is the master of R wrappers
